Added code to check application deploy status.

diff --git a/.github/actions/backend-deploy/files/cloudbuild.yaml b/.github/actions/backend-deploy/files/cloudbuild.yaml
--- a/.github/actions/backend-deploy/files/cloudbuild.yaml
+++ b/.github/actions/backend-deploy/files/cloudbuild.yaml
@@ -7,6 +7,8 @@ steps:
     #!/usr/bin/env bash
     set -euo pipefail
 
+    echo "Step 1: Prepare and setup service and cloud deploy manifest files"
+
     # Fetch project ID from 1Password and set up project variables
     PROJECT_ID=$(op read -n "op://CD/${_DEPLOYMENT_ENV}/${_APP_NAME}/DEPLOY_PROJECT_ID")
     echo "$PROJECT_ID" > /workspace/project_id.txt
@@ -50,7 +52,8 @@ steps:
     }
 
     targets=(${_DEPLOYMENT_ENVS})
-    if [ -z "${_DEPLOYMENT_ENV_FROM}" ] || [ "${_DEPLOYMENT_ENV_FROM}" = "${targets[0]}" ]; then
+    # If the deployment environment is the first in the list, update the Cloud Deploy manifest and generate service manifests
+    if [[ -z "${_DEPLOYMENT_ENV_FROM}" || "${_DEPLOYMENT_ENV}" == "${targets[0]}" ]]; then
       # Update Cloud Deploy manifest and generate service manifests
       yq e -i '.metadata.name = env(_DEPLOYMENT_PIPELINE)' "./devops/gcp/clouddeploy.yaml"
 
@@ -72,13 +75,14 @@ steps:
     #!/usr/bin/env bash
     set -euo pipefail
 
+    echo "Step 2: Build and deploy the application"
+
     # Set up environment variables
     PROJECT_ID=$(cat /workspace/project_id.txt)
     PROJECT_NAME=$(echo "$PROJECT_ID" | cut -d'-' -f 1)
     TARGET="${PROJECT_NAME}-${_DEPLOYMENT_ENV}"
     TARGET_FROM="${PROJECT_NAME}-${_DEPLOYMENT_ENV_FROM}"
     IMAGE_PATH="${_REGION}-docker.pkg.dev/${_BUILD_PROJECT}/cloud-run-repo/${_APP_NAME}"
-    RELEASE_TIMESTAMP=$(date '+%Y%m%d%H%M')
 
     # Function to check if tag exists in Google Artifact Registry
     tag_exists() {
@@ -95,11 +99,12 @@ steps:
     tag_image() {
       local source_tag="$1"
       local target_tag="$2"
-      if ! tag_exists "${source_tag}"; then
-        gcloud artifacts docker tags add \
-          "${IMAGE_PATH}:${source_tag}" \
-          "${IMAGE_PATH}:${target_tag}"
-      fi
+
+      echo "Tagging: ${source_tag} -> ${target_tag}"
+
+      gcloud artifacts docker tags add \
+        "${IMAGE_PATH}:${source_tag}" \
+        "${IMAGE_PATH}:${target_tag}"
     }
 
     # Function to build and push Docker image
@@ -150,24 +155,87 @@ steps:
     # Change to the devops/gcp directory, create a new release need the files in this directory
     cd ./devops/gcp
 
+    # Get the current active revision for the service
+    PREVIOUS_REVISION=$(gcloud run revisions list --service="${_APP_NAME}-${_DEPLOYMENT_ENV}" \
+        --filter="status.conditions.type:Active AND -status.conditions.status:'False'" \
+        --format='value(metadata.name)'\
+        --region="${_REGION}" \
+        --project="$PROJECT_ID")
+    echo "Previous active revision: $PREVIOUS_REVISION"
+
+    RELEASE_NAME="v-${_APP_NAME}-${_SHORT_SHA}-$(date '+%Y%m%d%H%M')"
+
     # Create new release or promote existing release
     if [ -z "${_DEPLOYMENT_ENV_FROM}" ] || [ "${_DEPLOYMENT_ENV_FROM}" = "${_DEPLOYMENT_ENV}" ]; then
-      gcloud deploy releases create "v-${_APP_NAME}-${_SHORT_SHA}-${RELEASE_TIMESTAMP}" \
+      gcloud deploy releases create "${RELEASE_NAME}" \
         --delivery-pipeline="${_DEPLOYMENT_PIPELINE}" \
         --region="${_REGION}" \
         --to-target="${TARGET}" \
         --images="image-placeholder=${IMAGE_PATH}:${_SHORT_SHA}"
     else
-      LATEST_RELEASE_NAME=$(gcloud deploy targets describe "${TARGET_FROM}" \
+      RELEASE_NAME=$(gcloud deploy targets describe "${TARGET_FROM}" \
             --delivery-pipeline="${_DEPLOYMENT_PIPELINE}" \
             --region="${_REGION}" \
             --format="value('Latest release')")
 
-      gcloud deploy releases promote --release="${LATEST_RELEASE_NAME}" \
+      gcloud deploy releases promote --release="${RELEASE_NAME}" \
         --delivery-pipeline="${_DEPLOYMENT_PIPELINE}" \
         --region="${_REGION}" \
         --to-target="${TARGET}"
     fi
+
+    # Wait for the release to be deployed
+    MAX_RETRIES=10
+    RETRY_INTERVAL=30
+    RETRY_COUNT=0
+
+    # Install required packages
+    apt-get update
+    apt-get install jq -y
+
+    # Remove the project ID from the release name if it exists
+    RELEASE_NAME=$(echo "$RELEASE_NAME" | awk -F'/' '{print $NF}')
+    echo "Release name: $RELEASE_NAME"
+
+    while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
+      RELEASE_STATUS=$(gcloud run revisions list --service="${_APP_NAME}-${_DEPLOYMENT_ENV}" \
+        --region="${_REGION}" \
+        --project="$PROJECT_ID" \
+        --filter="metadata.labels.release-id:${RELEASE_NAME}" \
+        --format="json" | jq  -r '.[].status.conditions[] | select (.type == "Ready") | .status')
+
+      if [ "${RELEASE_STATUS}" = "True" ]; then
+        echo "Release ${RELEASE_NAME} completed successfully."
+        break
+      elif [ "${RELEASE_STATUS}" = "False" ]; then
+        echo "Release ${RELEASE_NAME} failed with status: ${RELEASE_STATUS}"
+        exit 1
+      else
+        echo "Release ${RELEASE_NAME} is still in progress."
+        RETRY_COUNT=$((RETRY_COUNT + 1))
+        sleep $RETRY_INTERVAL
+      fi
+    done
+
+    if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
+      echo "Timeout waiting for release ${RELEASE_NAME} to complete."
+      exit 1
+    fi
+
+    # Get the new revision for the service
+    DEPLOYED_REVISION=$(gcloud run revisions list --service="${_APP_NAME}-${_DEPLOYMENT_ENV}" \
+        --filter="status.conditions.type:Active AND -status.conditions.status:'False'" \
+        --format='value(metadata.name)'\
+        --region="${_REGION}" \
+        --project="$PROJECT_ID")
+    echo "$DEPLOYED_REVISION" > /workspace/deployed_revision.txt
+    echo "Deployed revision: $DEPLOYED_REVISION"
+
+    # Update traffic to 0 for the new revision and wait for the new revision to be ready
+    gcloud run services update-traffic "${_APP_NAME}-${_DEPLOYMENT_ENV}" \
+        --region="${_REGION}" \
+        --project="$PROJECT_ID" \
+        --to-revisions="$PREVIOUS_REVISION=100"
 
 # Step 3: Trigger database migration job (if applicable)
 - name: 'gcr.io/cloud-builders/gcloud'
@@ -175,24 +243,45 @@ steps:
     #!/usr/bin/env bash
     set -euo pipefail
 
+    echo "Step 3: Trigger database migration job (if applicable) and update traffic to 100% for the new revision"
+
     # Check if migrations directory exists and execute migration job
     if [ -d "migrations" ]; then
-      DEPLOY_PROJECT_ID=$(cat /workspace/project_id.txt)
+      PROJECT_ID=$(cat /workspace/project_id.txt)
       JOB_NAME="${_APP_NAME}-db-migration-${_DEPLOYMENT_ENV}"
+      DEPLOYED_REVISION=$(cat /workspace/deployed_revision.txt)
 
-      echo "DEPLOY_PROJECT_ID: $DEPLOY_PROJECT_ID"
+      echo "DEPLOY_PROJECT_ID: $PROJECT_ID"
       echo "JOB_NAME: $JOB_NAME"
+      echo "DEPLOYED_REVISION: $DEPLOYED_REVISION"
 
-      if gcloud run jobs describe $JOB_NAME --project=${DEPLOY_PROJECT_ID} --region=${_REGION} 2> /dev/null ; then
-        gcloud run jobs execute "$JOB_NAME" \
-          --region="${_REGION}" \
-          --project="$DEPLOY_PROJECT_ID"
+      if gcloud run jobs describe $JOB_NAME --project=$PROJECT_ID --region=${_REGION} 2> /dev/null ; then
+        # Run the job and capture the output
+        JOB_OUTPUT=$(gcloud run jobs execute "$JOB_NAME" \
+            --region="${_REGION}" \
+            --project="$PROJECT_ID" \
+            --wait \
+            --format="value(status.conditions.type,status.conditions.message)")
+
+        if echo "$JOB_OUTPUT" | grep -q "Completed"; then
+          echo "Migration job completed."
+        else
+          echo "Migration job failed: $JOB_OUTPUT"
+          exit 1
+        fi
       else
         echo "Migration job $JOB_NAME does not exist. Skipping migration." >&2
+        exit 1
       fi
     else
       echo "Migrations folder does not exist. Skipping migration." >&2
     fi
+
+    # Update traffic to 100 for the new revision
+    gcloud run services update-traffic "${_APP_NAME}-${_DEPLOYMENT_ENV}" \
+        --region="${_REGION}" \
+        --project="$PROJECT_ID" \
+        --to-revisions="$DEPLOYED_REVISION=100"
 
 # Secret management
 availableSecrets:
